spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: sys
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: System
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true